[package]
name = "ctftools"
version = "0.1.0"
authors = ["Ben Lichtman"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
tokio = { version = "0.2", features = ["full"] }
futures = "0.3"
goblin = "0.2.1"
