[package]
name = "ctftools"
version = "0.1.1"
authors = ["Ben Lichtman"]
edition = "2018"
description = "Helper library for CTFs - based off pwntools for python3"
license = "MIT OR Apache-2.0"

[dependencies]
anyhow = "1.0.28"
goblin = "0.2.1"
checksec = "0.0.4"
sysexit = "0.2.0"
memmap = "0.7.0"
